source 'https://github.com/CocoaPods/Specs.git'

target 'DDLicenseViewController', :exclusive => true do
  pod "DDLicenseViewController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "DDLicenseViewController", :path => "../"

  
end
